---
title: "Going beyond ReLTER"
author: "Micha Silver"
date: "13/04/2022"
output:
  html_document:
    toc: true
    theme: united
---

<!-- [Back to TOC](index.html) -->

```{r setup4, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pkg_list <- c("sf", "terra", "ReLTER", "tmap")
lapply(pkg_list,require, character.only = TRUE)
```

## What can be done with ReLTER outputs 

```{r saving}
```

----

## Merging other data

The site boundary, obtained from https://DEIMS.org can be used to crop and mask EO data from other sources. In this section we show use of global EO data acquired from a new `R` package `geodata`. Elevation from the Shuttle Radar Terrain Mission (SRTM) and species distribution from Global Biodiversity Information Facility (GBIF) will be downloaded, cropped to a site boundary and compared. The Gran Paradiso National Park will be used, and this example will examine *Capra ibex* sitings

----


```{r merging}
# Get the geodata package
if (!require(geodata)) {
  install.packages("geodata", dependencies = TRUE)
  library(geodata)
}
# Get Gran Paradiso DEIMS ID
paradiso <- get_ilter_generalinfo(country_name = "Italy",
                                site_name = "Gran Paradiso")
paradiso_id <- paradiso[2,]$uri
paradiso_boundary <- get_site_info(paradiso_id, "Boundaries")
```

----

```{r get-geodata}
# Download SRTM tile centered on Northern Italy
italy_srtm <- elevation_3s(lon = 7.5, lat = 47.5, path = tempdir())
paradiso_srtm <- mask(crop(italy_srtm, vect(paradiso_boundary)),
                      vect(paradiso_boundary))
names(paradiso_srtm) <- "Elev"
# Query GBIF for *Capra ibex*
ibex <- sp_occurrence("Capra", species = "ibex",
                            ext = ext(paradiso_boundary))
ibex <- ibex[,c("lon", "lat")]
ibex <- ibex[complete.cases(ibex),]
ibex_points <- st_as_sf(ibex, coords = c("lon", "lat"), crs = "EPSG:4326")
```

----

```{r correlation}
ibex_elev <- extract(x = paradiso_srtm, y=vect(ibex_points))
ibex_points <- cbind(ibex_points, ibex_elev)
hist(ibex_points$Elev, breaks=20,
     main = "Distribution of Ibex sitings by elevation")
```

----

Prepare a plot, including hillshade effect

```{r ibex-plot}
# Create hillshade raster
slope <-  terrain(paradiso_srtm, "slope", unit = "radians")
aspect <-  terrain(paradiso_srtm, "aspect", unit="radians")
hill_shade = shade(slope, aspect, angle=35, direction = 310)
```

----

```{r ibex-plot2}
tm_basemap("OpenStreetMap.Mapnik") +
  tm_shape(hill_shade) +
  tm_raster(alpha = 0.4, palette = "Greys",
            n=8, legend.show = FALSE) +
  tm_shape(paradiso_boundary) +
  tm_borders(col = "purple", lwd = 2) +
  tm_shape(ibex_points) + 
  tm_symbols(size=0.2, col = "red") 
```

## Future plans
 - Acquire MODIS products
   * Time series
 - Acquire species distribution from GBIF: https://www.gbif.org/dataset/search
 - Acquire high resolution landcover data from ESA Worldcover: https://esa-worldcover.org/
 

<!-- [Back to TOC](index.html) -->